import type {
  Department,
  Resource,
  StaffMember,
  Ambulance,
  Patient,
  ResourceAllocation,
  SystemSettings,
  AuditEvent,
} from "../src/types";

export const SEED_VERSION = "shantideep-bengaluru-v2";

export const SEED_SETTINGS: SystemSettings = {
  id: "shantideep-settings",
  hospitalName: "Shantideep Multispeciality Hospital",
  priorityFormulaWeights: {
    urgencyWeight: 1.0,
    waitingWeight: 0.5,
    riskWeight: 0.8,
    resourceWeight: 0.4,
  },
  urgencyWeights: {
    CRITICAL: 100,
    HIGH: 60,
    MODERATE: 30,
    LOW: 10,
  },
  waitingAgingRatePer10Min: 5,
  emergencySurgeModeActive: false,
  surgeModeActive: false,
  staffShortageModeActive: false,
  doctorShortageCount: 0,
  nurseShortageCount: 0,
  maxWaitingThresholdMinutes: 45,
  maxConcurrentCasesPerDoctor: 3,
  activeStrategy: "PRIORITY_FIRST",
  updatedAt: new Date().toISOString(),
};

export const SEED_DEPARTMENTS: Department[] = [
  {
    id: "dept-er",
    name: "Emergency & Trauma",
    code: "ED",
    description: "24/7 Acute trauma, resuscitation, and critical emergency stabilization",
    maxCapacity: 20,
    isClosed: false,
    floor: "Ground Floor, Block A",
    headOfDepartment: "Dr. Anirudh Rao",
    bedCapacity: 12,
    currentOccupancy: 8,
    activeStaffCount: 8,
    color: "#ef4444",
  },
  {
    id: "dept-icu",
    name: "Intensive Care Unit (ICU)",
    code: "ICU",
    description: "Multi-disciplinary critical care, invasive hemodynamic monitoring, and mechanical ventilation",
    maxCapacity: 12,
    isClosed: false,
    floor: "2nd Floor, Critical Care Wing",
    headOfDepartment: "Dr. Vivek Nair",
    bedCapacity: 10,
    currentOccupancy: 7,
    activeStaffCount: 6,
    color: "#8b5cf6",
  },
  {
    id: "dept-med",
    name: "General Medicine",
    code: "MED",
    description: "Inpatient care for acute febrile illness, infectious diseases, and complex multi-system disorders",
    maxCapacity: 35,
    isClosed: false,
    floor: "3rd Floor, Inpatient Block",
    headOfDepartment: "Dr. Harish Kumar",
    bedCapacity: 25,
    currentOccupancy: 18,
    activeStaffCount: 7,
    color: "#3b82f6",
  },
  {
    id: "dept-cardio",
    name: "Cardiology",
    code: "CARD",
    description: "Comprehensive acute coronary syndrome care, cath lab, and telemetry monitoring",
    maxCapacity: 18,
    isClosed: false,
    floor: "1st Floor, Heart Center",
    headOfDepartment: "Dr. Kavitha Menon",
    bedCapacity: 14,
    currentOccupancy: 10,
    activeStaffCount: 5,
    color: "#ec4899",
  },
  {
    id: "dept-neuro",
    name: "Neurology",
    code: "NEUR",
    description: "Stroke unit, neurological critical care, and post-seizure inpatient monitoring",
    maxCapacity: 15,
    isClosed: false,
    floor: "4th Floor, Neuroscience Wing",
    headOfDepartment: "Dr. Shreya Kulkarni",
    bedCapacity: 12,
    currentOccupancy: 7,
    activeStaffCount: 4,
    color: "#6366f1",
  },
  {
    id: "dept-ortho",
    name: "Orthopedics",
    code: "ORTH",
    description: "Trauma reconstruction, joint replacement, and complex musculoskeletal trauma care",
    maxCapacity: 20,
    isClosed: false,
    floor: "2nd Floor, Surgical Block",
    headOfDepartment: "Dr. Rohit Bhat",
    bedCapacity: 15,
    currentOccupancy: 9,
    activeStaffCount: 4,
    color: "#14b8a6",
  },
  {
    id: "dept-surg",
    name: "General Surgery",
    code: "SURG",
    description: "Elective and acute abdominal surgery, laparoscopic procedures, and surgical ICU stepdown",
    maxCapacity: 16,
    isClosed: false,
    floor: "2nd Floor, Operation Theatres",
    headOfDepartment: "Dr. Arvind Reddy",
    bedCapacity: 12,
    currentOccupancy: 8,
    activeStaffCount: 5,
    color: "#f59e0b",
  },
  {
    id: "dept-obg",
    name: "Obstetrics & Gynecology",
    code: "OBG",
    description: "Labor suites, high-risk pregnancy monitoring, and comprehensive women's healthcare",
    maxCapacity: 22,
    isClosed: false,
    floor: "3rd Floor, Mother & Child Center",
    headOfDepartment: "Dr. Meenal Shah",
    bedCapacity: 18,
    currentOccupancy: 11,
    activeStaffCount: 5,
    color: "#f43f5e",
  },
  {
    id: "dept-ped",
    name: "Pediatrics & Neonatology",
    code: "PED",
    description: "Inpatient pediatric ward and high-dependency care for pediatric infectious and respiratory cases",
    maxCapacity: 18,
    isClosed: false,
    floor: "3rd Floor, Pediatrics Wing",
    headOfDepartment: "Dr. Priyanka Iyer",
    bedCapacity: 14,
    currentOccupancy: 7,
    activeStaffCount: 4,
    color: "#10b981",
  },
  {
    id: "dept-nephro",
    name: "Nephrology & Hemodialysis",
    code: "NEPH",
    description: "Dialysis station, acute kidney injury stabilization, and chronic renal care",
    maxCapacity: 14,
    isClosed: false,
    floor: "Ground Floor, Renal Care Wing",
    headOfDepartment: "Dr. Sanjay Patil",
    bedCapacity: 10,
    currentOccupancy: 6,
    activeStaffCount: 4,
    color: "#06b6d4",
  },
  {
    id: "dept-pulmo",
    name: "Pulmonology",
    code: "PULM",
    description: "Respiratory failure care, non-invasive ventilation, and severe asthma/COPD stabilization",
    maxCapacity: 16,
    isClosed: false,
    floor: "4th Floor, Chest Clinic Block",
    headOfDepartment: "Dr. Sneha Hegde",
    bedCapacity: 12,
    currentOccupancy: 8,
    activeStaffCount: 4,
    color: "#0ea5e9",
  },
  {
    id: "dept-rad",
    name: "Radiology & Imaging",
    code: "RAD",
    description: "24/7 128-Slice CT, 3T MRI, Digital X-Ray, and Ultrasonography support",
    maxCapacity: 10,
    isClosed: false,
    floor: "Basement 1, Diagnostic Center",
    headOfDepartment: "Dr. Lakshmi Narayanan",
    bedCapacity: 4,
    currentOccupancy: 2,
    activeStaffCount: 3,
    color: "#84cc16",
  },
  {
    id: "dept-lab",
    name: "Laboratory & Pathology",
    code: "LAB",
    description: "Automated hematology, clinical biochemistry, and rapid microbiology testing",
    maxCapacity: 10,
    isClosed: false,
    floor: "Basement 1, Diagnostic Center",
    headOfDepartment: "Dr. Divya Srinivasan",
    bedCapacity: 2,
    currentOccupancy: 1,
    activeStaffCount: 4,
    color: "#a855f7",
  },
  {
    id: "dept-pharm",
    name: "Inpatient Pharmacy",
    code: "PHARM",
    description: "24/7 Central inpatient medication dispensary and emergency medication supply",
    maxCapacity: 10,
    isClosed: false,
    floor: "Ground Floor, Main Concourse",
    headOfDepartment: "Aditi Kapoor, M.Pharm",
    bedCapacity: 0,
    currentOccupancy: 0,
    activeStaffCount: 4,
    color: "#64748b",
  },
];

export const SEED_STAFF: StaffMember[] = [
  {
    id: "staff-doc-01",
    name: "Dr. Anirudh Rao",
    role: "DOCTOR",
    departmentId: "dept-er",
    departmentName: "Emergency & Trauma",
    specialty: "Emergency Medicine",
    shiftStatus: "ON_DUTY",
    activeAllocationsCount: 2,
    maxConcurrentCases: 3,
  },
  {
    id: "staff-doc-02",
    name: "Dr. Kavitha Menon",
    role: "DOCTOR",
    departmentId: "dept-cardio",
    departmentName: "Cardiology",
    specialty: "Interventional Cardiology",
    shiftStatus: "ON_DUTY",
    activeAllocationsCount: 2,
    maxConcurrentCases: 3,
  },
  {
    id: "staff-doc-03",
    name: "Dr. Vivek Nair",
    role: "DOCTOR",
    departmentId: "dept-icu",
    departmentName: "Intensive Care Unit (ICU)",
    specialty: "Critical Care / Intensivist",
    shiftStatus: "ON_DUTY",
    activeAllocationsCount: 2,
    maxConcurrentCases: 2,
  },
  {
    id: "staff-doc-04",
    name: "Dr. Arvind Reddy",
    role: "DOCTOR",
    departmentId: "dept-surg",
    departmentName: "General Surgery",
    specialty: "Trauma & GI Surgery",
    shiftStatus: "ON_DUTY",
    activeAllocationsCount: 1,
    maxConcurrentCases: 2,
  },
  {
    id: "staff-doc-05",
    name: "Dr. Shreya Kulkarni",
    role: "DOCTOR",
    departmentId: "dept-neuro",
    departmentName: "Neurology",
    specialty: "Stroke & Neuro-Critical Care",
    shiftStatus: "ON_DUTY",
    activeAllocationsCount: 1,
    maxConcurrentCases: 3,
  },
  {
    id: "staff-doc-06",
    name: "Dr. Harish Kumar",
    role: "DOCTOR",
    departmentId: "dept-med",
    departmentName: "General Medicine",
    specialty: "Internal Medicine & Infectious Diseases",
    shiftStatus: "ON_DUTY",
    activeAllocationsCount: 2,
    maxConcurrentCases: 4,
  },
  {
    id: "staff-doc-07",
    name: "Dr. Rohit Bhat",
    role: "DOCTOR",
    departmentId: "dept-ortho",
    departmentName: "Orthopedics",
    specialty: "Orthopedic Trauma",
    shiftStatus: "ON_DUTY",
    activeAllocationsCount: 1,
    maxConcurrentCases: 3,
  },
  {
    id: "staff-doc-08",
    name: "Dr. Meenal Shah",
    role: "DOCTOR",
    departmentId: "dept-obg",
    departmentName: "Obstetrics & Gynecology",
    specialty: "High-Risk Obstetrics",
    shiftStatus: "ON_DUTY",
    activeAllocationsCount: 1,
    maxConcurrentCases: 3,
  },
  {
    id: "staff-doc-09",
    name: "Dr. Priyanka Iyer",
    role: "DOCTOR",
    departmentId: "dept-ped",
    departmentName: "Pediatrics & Neonatology",
    specialty: "Pediatric Critical Care",
    shiftStatus: "ON_DUTY",
    activeAllocationsCount: 1,
    maxConcurrentCases: 3,
  },
  {
    id: "staff-doc-10",
    name: "Dr. Sanjay Patil",
    role: "DOCTOR",
    departmentId: "dept-nephro",
    departmentName: "Nephrology & Hemodialysis",
    specialty: "Nephrology & Renal Transplant",
    shiftStatus: "ON_DUTY",
    activeAllocationsCount: 1,
    maxConcurrentCases: 3,
  },
  // Nurses
  {
    id: "staff-nur-01",
    name: "Deepa Nair, BSc RN",
    role: "NURSE",
    departmentId: "dept-er",
    departmentName: "Emergency & Trauma",
    specialty: "Emergency & Trauma Nursing (Shift 07:00-15:00)",
    shiftStatus: "ON_DUTY",
    activeAllocationsCount: 2,
    maxConcurrentCases: 3,
  },
  {
    id: "staff-nur-02",
    name: "Anitha Rao, GNM RN",
    role: "NURSE",
    departmentId: "dept-icu",
    departmentName: "Intensive Care Unit (ICU)",
    specialty: "Critical Care Nursing (Shift 07:00-15:00)",
    shiftStatus: "ON_DUTY",
    activeAllocationsCount: 2,
    maxConcurrentCases: 2,
  },
  {
    id: "staff-nur-03",
    name: "Swathi K., BSc RN",
    role: "NURSE",
    departmentId: "dept-cardio",
    departmentName: "Cardiology",
    specialty: "Cardiac Care Nursing (Shift 07:00-15:00)",
    shiftStatus: "ON_DUTY",
    activeAllocationsCount: 2,
    maxConcurrentCases: 3,
  },
  {
    id: "staff-nur-04",
    name: "Manjula Shetty, RN",
    role: "NURSE",
    departmentId: "dept-med",
    departmentName: "General Medicine",
    specialty: "Inpatient Ward Nursing (Shift 07:00-15:00)",
    shiftStatus: "ON_DUTY",
    activeAllocationsCount: 2,
    maxConcurrentCases: 4,
  },
  {
    id: "staff-nur-05",
    name: "Asha Joseph, BSc RN",
    role: "NURSE",
    departmentId: "dept-surg",
    departmentName: "General Surgery",
    specialty: "Perioperative Nursing (Shift 07:00-15:00)",
    shiftStatus: "ON_DUTY",
    activeAllocationsCount: 1,
    maxConcurrentCases: 3,
  },
  {
    id: "staff-nur-06",
    name: "Reshma Patil, RN",
    role: "NURSE",
    departmentId: "dept-ped",
    departmentName: "Pediatrics & Neonatology",
    specialty: "Pediatric Nursing (Shift 15:00-23:00)",
    shiftStatus: "ON_CALL",
    activeAllocationsCount: 0,
    maxConcurrentCases: 3,
  },
];

export const SEED_RESOURCES: Resource[] = [
  // Emergency Beds
  { id: "res-er-01", resourceNumber: "ER-01", name: "Emergency Resuscitation Bay 1", type: "BED", departmentId: "dept-er", departmentName: "Emergency & Trauma", capacity: 1, status: "IN_USE", assignedPatientName: "Ramesh Gowda", location: "ED Trauma Wing", updatedAt: new Date().toISOString() },
  { id: "res-er-02", resourceNumber: "ER-02", name: "Emergency Acute Bay 2", type: "BED", departmentId: "dept-er", departmentName: "Emergency & Trauma", capacity: 1, status: "IN_USE", assignedPatientName: "Vikram Reddy", location: "ED Trauma Wing", updatedAt: new Date().toISOString() },
  { id: "res-er-03", resourceNumber: "ER-03", name: "Emergency Acute Bay 3", type: "BED", departmentId: "dept-er", departmentName: "Emergency & Trauma", capacity: 1, status: "AVAILABLE", location: "ED Acute Bay", updatedAt: new Date().toISOString() },
  { id: "res-er-04", resourceNumber: "ER-04", name: "Emergency Acute Bay 4", type: "BED", departmentId: "dept-er", departmentName: "Emergency & Trauma", capacity: 1, status: "AVAILABLE", location: "ED Acute Bay", updatedAt: new Date().toISOString() },
  { id: "res-er-05", resourceNumber: "ER-05", name: "Emergency Observation Bed 5", type: "BED", departmentId: "dept-er", departmentName: "Emergency & Trauma", capacity: 1, status: "AVAILABLE", location: "ED Observation Bay", updatedAt: new Date().toISOString() },
  { id: "res-er-06", resourceNumber: "ER-06", name: "Emergency Observation Bed 6", type: "BED", departmentId: "dept-er", departmentName: "Emergency & Trauma", capacity: 1, status: "MAINTENANCE", maintenanceReason: "Sanitization & Oxygen manifold calibration", location: "ED Observation Bay", updatedAt: new Date().toISOString() },

  // ICU Beds (10 total: 7 in use, 1 reserved, 1 maintenance, 1 available)
  { id: "res-icu-01", resourceNumber: "ICU-01", name: "ICU Bed 01 (Isolation Negative Pressure)", type: "ICU_BED", departmentId: "dept-icu", departmentName: "Intensive Care Unit (ICU)", capacity: 1, status: "IN_USE", assignedPatientName: "Mohammed Farooq", location: "ICU Isolation Pod", updatedAt: new Date().toISOString() },
  { id: "res-icu-02", resourceNumber: "ICU-02", name: "ICU Bed 02", type: "ICU_BED", departmentId: "dept-icu", departmentName: "Intensive Care Unit (ICU)", capacity: 1, status: "IN_USE", assignedPatientName: "Lakshmi Narayanan", location: "ICU Main Pod", updatedAt: new Date().toISOString() },
  { id: "res-icu-03", resourceNumber: "ICU-03", name: "ICU Bed 03", type: "ICU_BED", departmentId: "dept-icu", departmentName: "Intensive Care Unit (ICU)", capacity: 1, status: "IN_USE", assignedPatientName: "Sanjay Patil", location: "ICU Main Pod", updatedAt: new Date().toISOString() },
  { id: "res-icu-04", resourceNumber: "ICU-04", name: "ICU Bed 04", type: "ICU_BED", departmentId: "dept-icu", departmentName: "Intensive Care Unit (ICU)", capacity: 1, status: "IN_USE", assignedPatientName: "Pooja Deshmukh", location: "ICU Main Pod", updatedAt: new Date().toISOString() },
  { id: "res-icu-05", resourceNumber: "ICU-05", name: "ICU Bed 05", type: "ICU_BED", departmentId: "dept-icu", departmentName: "Intensive Care Unit (ICU)", capacity: 1, status: "IN_USE", assignedPatientName: "Harish Kumar", location: "ICU Main Pod", updatedAt: new Date().toISOString() },
  { id: "res-icu-06", resourceNumber: "ICU-06", name: "ICU Bed 06", type: "ICU_BED", departmentId: "dept-icu", departmentName: "Intensive Care Unit (ICU)", capacity: 1, status: "IN_USE", assignedPatientName: "Kavya Shetty", location: "ICU Main Pod", updatedAt: new Date().toISOString() },
  { id: "res-icu-07", resourceNumber: "ICU-07", name: "ICU Bed 07", type: "ICU_BED", departmentId: "dept-icu", departmentName: "Intensive Care Unit (ICU)", capacity: 1, status: "IN_USE", assignedPatientName: "Sneha Kulkarni", location: "ICU Main Pod", updatedAt: new Date().toISOString() },
  { id: "res-icu-08", resourceNumber: "ICU-08", name: "ICU Bed 08 (Post-Surgical Stepdown)", type: "ICU_BED", departmentId: "dept-icu", departmentName: "Intensive Care Unit (ICU)", capacity: 1, status: "RESERVED", location: "ICU Stepdown Pod", updatedAt: new Date().toISOString() },
  { id: "res-icu-09", resourceNumber: "ICU-09", name: "ICU Bed 09", type: "ICU_BED", departmentId: "dept-icu", departmentName: "Intensive Care Unit (ICU)", capacity: 1, status: "MAINTENANCE", maintenanceReason: "HEPA air filtration inspection", location: "ICU Main Pod", updatedAt: new Date().toISOString() },
  { id: "res-icu-10", resourceNumber: "ICU-10", name: "ICU Bed 10", type: "ICU_BED", departmentId: "dept-icu", departmentName: "Intensive Care Unit (ICU)", capacity: 1, status: "AVAILABLE", location: "ICU Main Pod", updatedAt: new Date().toISOString() },

  // General Inpatient Beds
  { id: "res-gb-01", resourceNumber: "GB-01", name: "General Ward Bed 01", type: "BED", departmentId: "dept-med", departmentName: "General Medicine", capacity: 1, status: "IN_USE", assignedPatientName: "Nandini Krishnan", location: "Ward 3A", updatedAt: new Date().toISOString() },
  { id: "res-gb-02", resourceNumber: "GB-02", name: "General Ward Bed 02", type: "BED", departmentId: "dept-med", departmentName: "General Medicine", capacity: 1, status: "IN_USE", assignedPatientName: "Arjun Rao", location: "Ward 3A", updatedAt: new Date().toISOString() },
  { id: "res-gb-03", resourceNumber: "GB-03", name: "General Ward Bed 03", type: "BED", departmentId: "dept-med", departmentName: "General Medicine", capacity: 1, status: "AVAILABLE", location: "Ward 3A", updatedAt: new Date().toISOString() },
  { id: "res-gb-04", resourceNumber: "GB-04", name: "General Ward Bed 04", type: "BED", departmentId: "dept-med", departmentName: "General Medicine", capacity: 1, status: "AVAILABLE", location: "Ward 3B", updatedAt: new Date().toISOString() },
  { id: "res-gb-05", resourceNumber: "GB-05", name: "Cardiology Telemetry Bed 05", type: "BED", departmentId: "dept-cardio", departmentName: "Cardiology", capacity: 1, status: "IN_USE", assignedPatientName: "Ananya Iyer", location: "Cardio Stepdown", updatedAt: new Date().toISOString() },
  { id: "res-gb-06", resourceNumber: "GB-06", name: "Cardiology Telemetry Bed 06", type: "BED", departmentId: "dept-cardio", departmentName: "Cardiology", capacity: 1, status: "AVAILABLE", location: "Cardio Stepdown", updatedAt: new Date().toISOString() },
  { id: "res-gb-07", resourceNumber: "GB-07", name: "Neurology Care Bed 07", type: "BED", departmentId: "dept-neuro", departmentName: "Neurology", capacity: 1, status: "IN_USE", assignedPatientName: "Rahul Verma", location: "Neuro Ward 4A", updatedAt: new Date().toISOString() },
  { id: "res-gb-08", resourceNumber: "GB-08", name: "Orthopedic Traction Bed 08", type: "BED", departmentId: "dept-ortho", departmentName: "Orthopedics", capacity: 1, status: "IN_USE", assignedPatientName: "Aarav Sharma", location: "Ortho Ward 2B", updatedAt: new Date().toISOString() },
  { id: "res-gb-09", resourceNumber: "GB-09", name: "Surgical Recovery Bed 09", type: "BED", departmentId: "dept-surg", departmentName: "General Surgery", capacity: 1, status: "IN_USE", assignedPatientName: "Priya Menon", location: "Surgical Stepdown", updatedAt: new Date().toISOString() },
  { id: "res-gb-10", resourceNumber: "GB-10", name: "Pediatric Inpatient Bed 10", type: "BED", departmentId: "dept-ped", departmentName: "Pediatrics & Neonatology", capacity: 1, status: "IN_USE", assignedPatientName: "Meera Krishnan", location: "Pediatric Ward 3C", updatedAt: new Date().toISOString() },
  { id: "res-gb-11", resourceNumber: "GB-11", name: "Obstetric Ante-Natal Bed 11", type: "BED", departmentId: "dept-obg", departmentName: "Obstetrics & Gynecology", capacity: 1, status: "AVAILABLE", location: "Maternity Ward 3D", updatedAt: new Date().toISOString() },
  { id: "res-gb-12", resourceNumber: "GB-12", name: "General Ward Bed 12", type: "BED", departmentId: "dept-med", departmentName: "General Medicine", capacity: 1, status: "AVAILABLE", location: "Ward 3B", updatedAt: new Date().toISOString() },

  // Operating Rooms
  { id: "res-or-01", resourceNumber: "OR-01", name: "Major Operation Theatre 1 (Emergency Trauma)", type: "OPERATING_ROOM", departmentId: "dept-surg", departmentName: "General Surgery", capacity: 1, status: "IN_USE", assignedPatientName: "Priya Menon", location: "OT Complex, 2nd Floor", updatedAt: new Date().toISOString() },
  { id: "res-or-02", resourceNumber: "OR-02", name: "Major Operation Theatre 2 (Orthopedics & Neuro)", type: "OPERATING_ROOM", departmentId: "dept-ortho", departmentName: "Orthopedics", capacity: 1, status: "AVAILABLE", location: "OT Complex, 2nd Floor", updatedAt: new Date().toISOString() },
  { id: "res-or-03", resourceNumber: "OR-03", name: "Cardiac Cath Lab & Hybrid OR 3", type: "OPERATING_ROOM", departmentId: "dept-cardio", departmentName: "Cardiology", capacity: 1, status: "RESERVED", location: "Heart Center, 1st Floor", updatedAt: new Date().toISOString() },
  { id: "res-or-04", resourceNumber: "OR-04", name: "Day Care & Laparoscopic OR 4", type: "OPERATING_ROOM", departmentId: "dept-surg", departmentName: "General Surgery", capacity: 1, status: "AVAILABLE", location: "OT Complex, 2nd Floor", updatedAt: new Date().toISOString() },

  // Ventilators
  { id: "res-vent-01", resourceNumber: "VENT-01", name: "Hamilton C6 Intensive Ventilator", type: "VENTILATOR", departmentId: "dept-icu", departmentName: "Intensive Care Unit (ICU)", capacity: 1, status: "IN_USE", assignedPatientName: "Mohammed Farooq", location: "ICU Bed 01", updatedAt: new Date().toISOString() },
  { id: "res-vent-02", resourceNumber: "VENT-02", name: "Dräger Evita V800 Ventilator", type: "VENTILATOR", departmentId: "dept-icu", departmentName: "Intensive Care Unit (ICU)", capacity: 1, status: "IN_USE", assignedPatientName: "Lakshmi Narayanan", location: "ICU Bed 02", updatedAt: new Date().toISOString() },
  { id: "res-vent-03", resourceNumber: "VENT-03", name: "Maquet Servo-u ICU Ventilator", type: "VENTILATOR", departmentId: "dept-icu", departmentName: "Intensive Care Unit (ICU)", capacity: 1, status: "AVAILABLE", location: "ICU Equipment Bay", updatedAt: new Date().toISOString() },
  { id: "res-vent-04", resourceNumber: "VENT-04", name: "Philips Respironics BiPAP Focus", type: "VENTILATOR", departmentId: "dept-pulmo", departmentName: "Pulmonology", capacity: 1, status: "AVAILABLE", location: "Pulmonology Stepdown", updatedAt: new Date().toISOString() },

  // Specialized Equipment (Cardiac Monitors, Dialysis)
  { id: "res-cm-01", resourceNumber: "CM-01", name: "Mindray BeneVision Multi-Parameter Monitor", type: "EQUIPMENT", departmentId: "dept-er", departmentName: "Emergency & Trauma", capacity: 1, status: "IN_USE", assignedPatientName: "Ramesh Gowda", location: "ER Bay 1", updatedAt: new Date().toISOString() },
  { id: "res-cm-02", resourceNumber: "CM-02", name: "GE Solar 8000i Multi-Lead ECG Monitor", type: "EQUIPMENT", departmentId: "dept-cardio", departmentName: "Cardiology", capacity: 1, status: "IN_USE", assignedPatientName: "Ananya Iyer", location: "Cardio Stepdown", updatedAt: new Date().toISOString() },
  { id: "res-cm-03", resourceNumber: "CM-03", name: "Mindray BeneVision N17 Monitor", type: "EQUIPMENT", departmentId: "dept-er", departmentName: "Emergency & Trauma", capacity: 1, status: "AVAILABLE", location: "ED Equipment Bay", updatedAt: new Date().toISOString() },
  { id: "res-dia-01", resourceNumber: "DIA-01", name: "Fresenius 4008S Hemodialysis Machine", type: "EQUIPMENT", departmentId: "dept-nephro", departmentName: "Nephrology & Hemodialysis", capacity: 1, status: "IN_USE", assignedPatientName: "Sanjay Patil", location: "Dialysis Unit Bed 1", updatedAt: new Date().toISOString() },
  { id: "res-dia-02", resourceNumber: "DIA-02", name: "Fresenius 5008 High-Flux Dialysis Machine", type: "EQUIPMENT", departmentId: "dept-nephro", departmentName: "Nephrology & Hemodialysis", capacity: 1, status: "AVAILABLE", location: "Dialysis Station 2", updatedAt: new Date().toISOString() },

  // Doctors & Nurses registered as resources
  { id: "res-doc-01", resourceNumber: "DOC-01", name: "Dr. Anirudh Rao (Emergency)", type: "DOCTOR", departmentId: "dept-er", departmentName: "Emergency & Trauma", capacity: 3, status: "AVAILABLE", updatedAt: new Date().toISOString() },
  { id: "res-doc-02", resourceNumber: "DOC-02", name: "Dr. Kavitha Menon (Cardiology)", type: "DOCTOR", departmentId: "dept-cardio", departmentName: "Cardiology", capacity: 3, status: "AVAILABLE", updatedAt: new Date().toISOString() },
  { id: "res-doc-03", resourceNumber: "DOC-03", name: "Dr. Vivek Nair (Critical Care)", type: "DOCTOR", departmentId: "dept-icu", departmentName: "Intensive Care Unit (ICU)", capacity: 2, status: "AVAILABLE", updatedAt: new Date().toISOString() },
  { id: "res-doc-04", resourceNumber: "DOC-04", name: "Dr. Arvind Reddy (Surgery)", type: "DOCTOR", departmentId: "dept-surg", departmentName: "General Surgery", capacity: 2, status: "AVAILABLE", updatedAt: new Date().toISOString() },
  { id: "res-doc-06", resourceNumber: "DOC-06", name: "Dr. Harish Kumar (General Medicine)", type: "DOCTOR", departmentId: "dept-med", departmentName: "General Medicine", capacity: 4, status: "AVAILABLE", updatedAt: new Date().toISOString() },

  { id: "res-nur-01", resourceNumber: "NUR-01", name: "Deepa Nair, BSc RN", type: "NURSE", departmentId: "dept-er", departmentName: "Emergency & Trauma", capacity: 3, status: "AVAILABLE", updatedAt: new Date().toISOString() },
  { id: "res-nur-02", resourceNumber: "NUR-02", name: "Anitha Rao, GNM RN", type: "NURSE", departmentId: "dept-icu", departmentName: "Intensive Care Unit (ICU)", capacity: 2, status: "AVAILABLE", updatedAt: new Date().toISOString() },
  { id: "res-nur-03", resourceNumber: "NUR-03", name: "Swathi K., BSc RN", type: "NURSE", departmentId: "dept-cardio", departmentName: "Cardiology", capacity: 3, status: "AVAILABLE", updatedAt: new Date().toISOString() },
  { id: "res-nur-04", resourceNumber: "NUR-04", name: "Manjula Shetty, RN", type: "NURSE", departmentId: "dept-med", departmentName: "General Medicine", capacity: 4, status: "AVAILABLE", updatedAt: new Date().toISOString() },
];

export const SEED_AMBULANCES: Ambulance[] = [
  {
    id: "amb-01",
    vehicleNumber: "KA-01-MJ-4412",
    unitNumber: "AMB-01",
    status: "AVAILABLE",
    driverName: "Manjunath Gowda",
    paramedicName: "Suresh Babu, EMT-P",
    equipmentSummary: "Advanced Cardiac Life Support (ACLS), Zoll X Series Defibrillator, Transport Ventilator",
    latitude: 12.9716,
    longitude: 77.5946,
    locationAddress: "Shantideep Emergency Trauma Bay, Bengaluru",
    estimatedArrivalMinutes: 0,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "amb-02",
    vehicleNumber: "KA-03-AB-8809",
    unitNumber: "AMB-02",
    status: "EN_ROUTE",
    driverName: "Basavaraj Patil",
    paramedicName: "Girish Kumar, EMT",
    equipmentSummary: "Basic Life Support (BLS), Automated External Defibrillator (AED), Trauma Immobilization Kit",
    latitude: 12.9784,
    longitude: 77.6408,
    locationAddress: "Indiranagar 100ft Road, Bengaluru",
    estimatedArrivalMinutes: 8,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "amb-03",
    vehicleNumber: "KA-05-EX-2134",
    unitNumber: "AMB-03",
    status: "DISPATCHED",
    driverName: "Chetan Kumar",
    paramedicName: "Praveen Shenoy, EMT-P",
    equipmentSummary: "Advanced Life Support (ALS), Portable Multipara Monitor, Suction Unit",
    latitude: 12.9352,
    longitude: 77.6245,
    locationAddress: "Koramangala 80ft Road, Bengaluru",
    estimatedArrivalMinutes: 14,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "amb-04",
    vehicleNumber: "KA-51-MD-9041",
    unitNumber: "AMB-04",
    status: "AT_HOSPITAL",
    driverName: "Venkatesh Murthy",
    paramedicName: "Kavitha R., EMT",
    equipmentSummary: "Neonatal & Pediatric Transport Ambulance, Incubator, Resuscitator",
    latitude: 12.9716,
    longitude: 77.5946,
    locationAddress: "Shantideep Hospital Ambulance Bay 2, Bengaluru",
    estimatedArrivalMinutes: 0,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "amb-05",
    vehicleNumber: "KA-04-MK-1120",
    unitNumber: "AMB-05",
    status: "MAINTENANCE",
    driverName: "Raghavendra Hegde",
    paramedicName: "Sunil Shenoy, EMT",
    equipmentSummary: "Routine vehicle brake service & oxygen regulator certification",
    latitude: 12.9121,
    longitude: 77.6446,
    locationAddress: "HSR Layout Fleet Maintenance Workshop, Bengaluru",
    estimatedArrivalMinutes: 0,
    updatedAt: new Date().toISOString(),
  },
];

// Helper to compute ISO timestamp relative to now
const minsAgo = (mins: number) => new Date(Date.now() - mins * 60 * 1000).toISOString();

export const SEED_PATIENTS: Patient[] = [
  // ================= CRITICAL PATIENTS (~10%) =================
  {
    id: "pat-in-01",
    mrn: "MRN-BLR-2026-081",
    name: "Ramesh Gowda",
    age: 62,
    gender: "Male",
    contact: "+91 98450 12891",
    arrivalTime: minsAgo(18),
    symptoms: "Crushing retrosternal chest pain, diaphoresis, radiating to left jaw, severe breathlessness",
    clinicalNotes: "Patient arrived via ambulance from Jayanagar. ST-segment elevation noted in V2-V4 on ECG. Immediate cath lab evaluation required.",
    departmentId: "dept-er",
    departmentName: "Emergency & Trauma",
    vitalSigns: { heartRate: 118, bloodPressureSystolic: 88, bloodPressureDiastolic: 56, oxygenSaturation: 89, respiratoryRate: 28, temperatureCelsius: 36.8 },
    knownConditions: ["Hypertension", "Type 2 Diabetes Mellitus"],
    allergies: ["Penicillin"],
    requiredTreatment: "Immediate cardiology evaluation, coronary angiogram, cardiac monitoring",
    emergencyStatus: true,
    urgencyLevel: "CRITICAL",
    priorityScore: 98,
    priorityExplanation: "CRITICAL urgency (+100) with severe hypoxia (SpO2 89%), hypotension, and acute coronary risk.",
    waitingMinutes: 18,
    status: "ALLOCATED",
    createdAt: minsAgo(18),
    updatedAt: minsAgo(2),
  },
  {
    id: "pat-in-02",
    mrn: "MRN-BLR-2026-082",
    name: "Mohammed Farooq",
    age: 54,
    gender: "Male",
    contact: "+91 98860 34102",
    arrivalTime: minsAgo(45),
    symptoms: "Severe respiratory distress, altered sensorium, productive cough with hemoptysis",
    clinicalNotes: "Acute respiratory failure secondary to severe community-acquired pneumonia. Arterial blood gas shows severe hypoxemic respiratory failure. Intubated in ED.",
    departmentId: "dept-icu",
    departmentName: "Intensive Care Unit (ICU)",
    vitalSigns: { heartRate: 132, bloodPressureSystolic: 84, bloodPressureDiastolic: 50, oxygenSaturation: 84, respiratoryRate: 34, temperatureCelsius: 39.2 },
    knownConditions: ["Chronic Obstructive Pulmonary Disease"],
    allergies: ["None"],
    requiredTreatment: "Mechanical ventilation, invasive arterial line monitoring, IV broad-spectrum antibiotics",
    emergencyStatus: true,
    urgencyLevel: "CRITICAL",
    priorityScore: 104,
    priorityExplanation: "CRITICAL urgency (+100) with life-threatening hypoxia (SpO2 84%) and septic shock physiology.",
    waitingMinutes: 45,
    status: "ALLOCATED",
    createdAt: minsAgo(45),
    updatedAt: minsAgo(5),
  },
  {
    id: "pat-in-03",
    mrn: "MRN-BLR-2026-083",
    name: "Vikram Reddy",
    age: 29,
    gender: "Male",
    contact: "+91 98490 87234",
    arrivalTime: minsAgo(22),
    symptoms: "Blunt polytrauma following high-velocity two-wheeler collision on Hosur Road. Severe pelvic pain, hypovolemia",
    clinicalNotes: "GCS 13. Pelvic binder placed by EMT. Ultrasound FAST positive for free fluid in Morrison's pouch. Emergency blood transfusion initiated.",
    departmentId: "dept-er",
    departmentName: "Emergency & Trauma",
    vitalSigns: { heartRate: 126, bloodPressureSystolic: 86, bloodPressureDiastolic: 54, oxygenSaturation: 91, respiratoryRate: 26, temperatureCelsius: 36.4 },
    knownConditions: ["No prior medical history"],
    allergies: ["None reported"],
    requiredTreatment: "Emergency laparotomy, orthopedic external fixation, whole blood transfusion",
    emergencyStatus: true,
    urgencyLevel: "CRITICAL",
    priorityScore: 96,
    priorityExplanation: "CRITICAL urgency (+100) with active hemorrhagic shock and hemoperitoneum.",
    waitingMinutes: 22,
    status: "ALLOCATED",
    createdAt: minsAgo(22),
    updatedAt: minsAgo(4),
  },
  {
    id: "pat-in-04",
    mrn: "MRN-BLR-2026-084",
    name: "Lakshmi Narayanan",
    age: 71,
    gender: "Female",
    contact: "+91 98401 56789",
    arrivalTime: minsAgo(62),
    symptoms: "Acute onset right-sided hemiplegia and expressive aphasia, onset 75 minutes prior to presentation",
    clinicalNotes: "Suspected acute ischemic stroke in left MCA territory. CT Brain non-contrast excludes hemorrhage. NIH Stroke Scale score 16. Thrombolysis protocol initiated.",
    departmentId: "dept-neuro",
    departmentName: "Neurology",
    vitalSigns: { heartRate: 92, bloodPressureSystolic: 178, bloodPressureDiastolic: 102, oxygenSaturation: 95, respiratoryRate: 20, temperatureCelsius: 37.1 },
    knownConditions: ["Atrial Fibrillation", "Hypertension"],
    allergies: ["Sulfa drugs"],
    requiredTreatment: "IV Tenecteplase thrombolysis, continuous neurological monitoring, stroke unit bed",
    emergencyStatus: true,
    urgencyLevel: "CRITICAL",
    priorityScore: 94,
    priorityExplanation: "CRITICAL urgency (+100) within narrow therapeutic window for acute stroke thrombolysis.",
    waitingMinutes: 62,
    status: "ALLOCATED",
    createdAt: minsAgo(62),
    updatedAt: minsAgo(8),
  },

  // ================= HIGH URGENCY PATIENTS (~22%) =================
  {
    id: "pat-in-05",
    mrn: "MRN-BLR-2026-085",
    name: "Priya Menon",
    age: 26,
    gender: "Female",
    contact: "+91 98470 23419",
    arrivalTime: minsAgo(50),
    symptoms: "Severe right iliac fossa abdominal pain for 18 hours, migratory from umbilicus, vomiting and high fever",
    clinicalNotes: "Marked tenderness at McBurney's point with guarding. USG Abdomen confirms acute gangrenous appendicitis with periappendiceal fat stranding.",
    departmentId: "dept-surg",
    departmentName: "General Surgery",
    vitalSigns: { heartRate: 104, bloodPressureSystolic: 112, bloodPressureDiastolic: 72, oxygenSaturation: 98, respiratoryRate: 22, temperatureCelsius: 38.6 },
    knownConditions: ["None"],
    allergies: ["None"],
    requiredTreatment: "Emergency laparoscopic appendectomy, IV analgesia and pre-op antibiotics",
    emergencyStatus: true,
    urgencyLevel: "HIGH",
    priorityScore: 78,
    priorityExplanation: "HIGH urgency (+70) with surgical abdomen and risk of imminent perforation.",
    waitingMinutes: 50,
    status: "ALLOCATED",
    createdAt: minsAgo(50),
    updatedAt: minsAgo(12),
  },
  {
    id: "pat-in-06",
    mrn: "MRN-BLR-2026-086",
    name: "Sneha Kulkarni",
    age: 48,
    gender: "Female",
    contact: "+91 98220 44512",
    arrivalTime: minsAgo(38),
    symptoms: "High-grade fever with chills for 5 days, severe retro-orbital headache, diffuse petechiae, gum bleed",
    clinicalNotes: "Suspected severe dengue fever with thrombocytopenia under evaluation. Complete blood count shows platelets 22,000/mcL, hematocrit 46%. Dengue NS1 antigen positive.",
    departmentId: "dept-med",
    departmentName: "General Medicine",
    vitalSigns: { heartRate: 108, bloodPressureSystolic: 96, bloodPressureDiastolic: 64, oxygenSaturation: 96, respiratoryRate: 22, temperatureCelsius: 39.4 },
    knownConditions: ["Hypothyroidism"],
    allergies: ["Aspirin"],
    requiredTreatment: "Platelet transfusion reserve, tight fluid resuscitation protocol, close hematocrit tracking",
    emergencyStatus: true,
    urgencyLevel: "HIGH",
    priorityScore: 75,
    priorityExplanation: "HIGH urgency (+70) with critical thrombocytopenia and hemorrhagic warning signs.",
    waitingMinutes: 38,
    status: "ALLOCATED",
    createdAt: minsAgo(38),
    updatedAt: minsAgo(10),
  },
  {
    id: "pat-in-07",
    mrn: "MRN-BLR-2026-087",
    name: "Aarav Sharma",
    age: 38,
    gender: "Male",
    contact: "+91 98110 99823",
    arrivalTime: minsAgo(30),
    symptoms: "Compound fracture of right tibia and fibula following motorcycle slip on wet asphalt, active oozing",
    clinicalNotes: "Gustilo-Anderson Grade II open fracture. Wound cleansed and dressed with sterile pack. Peripheral pulses palpable and warm.",
    departmentId: "dept-ortho",
    departmentName: "Orthopedics",
    vitalSigns: { heartRate: 98, bloodPressureSystolic: 128, bloodPressureDiastolic: 82, oxygenSaturation: 99, respiratoryRate: 18, temperatureCelsius: 37.0 },
    knownConditions: ["None"],
    allergies: ["None"],
    requiredTreatment: "Wound debridement, IV cephalosporin, surgical reduction and internal fixation",
    emergencyStatus: true,
    urgencyLevel: "HIGH",
    priorityScore: 71,
    priorityExplanation: "HIGH urgency (+70) open fracture requiring debridement within 6-hour surgical window.",
    waitingMinutes: 30,
    status: "ALLOCATED",
    createdAt: minsAgo(30),
    updatedAt: minsAgo(6),
  },
  {
    id: "pat-in-08",
    mrn: "MRN-BLR-2026-088",
    name: "Ananya Iyer",
    age: 58,
    gender: "Female",
    contact: "+91 98410 77621",
    arrivalTime: minsAgo(25),
    symptoms: "Atypical epigastric burning, nausea, diaphoresis, and progressive fatigue in post-menopausal diabetic female",
    clinicalNotes: "Troponin I elevated at 0.42 ng/mL. Non-ST-elevation myocardial infarction (NSTEMI) under evaluation. Cardiology consult requested.",
    departmentId: "dept-cardio",
    departmentName: "Cardiology",
    vitalSigns: { heartRate: 94, bloodPressureSystolic: 146, bloodPressureDiastolic: 92, oxygenSaturation: 97, respiratoryRate: 20, temperatureCelsius: 36.9 },
    knownConditions: ["Type 2 Diabetes Mellitus", "Dyslipidemia"],
    allergies: ["None"],
    requiredTreatment: "Dual antiplatelet therapy, anticoagulation, telemetry monitoring, early invasive strategy",
    emergencyStatus: true,
    urgencyLevel: "HIGH",
    priorityScore: 73,
    priorityExplanation: "HIGH urgency (+70) confirmed biomarker-positive acute coronary syndrome.",
    waitingMinutes: 25,
    status: "ALLOCATED",
    createdAt: minsAgo(25),
    updatedAt: minsAgo(5),
  },
  {
    id: "pat-in-09",
    mrn: "MRN-BLR-2026-089",
    name: "Sanjay Patil",
    age: 65,
    gender: "Male",
    contact: "+91 98230 65123",
    arrivalTime: minsAgo(55),
    symptoms: "Oliguria for 24 hours, bilateral lower limb anasarca, progressive dyspnea and severe hyperkalemia",
    clinicalNotes: "Known CKD Stage 4 presenting with acute-on-chronic kidney injury. Serum potassium 6.8 mEq/L with peaked T-waves on ECG. Emergency dialysis required.",
    departmentId: "dept-nephro",
    departmentName: "Nephrology & Hemodialysis",
    vitalSigns: { heartRate: 78, bloodPressureSystolic: 172, bloodPressureDiastolic: 98, oxygenSaturation: 94, respiratoryRate: 24, temperatureCelsius: 36.7 },
    knownConditions: ["Chronic Kidney Disease", "Hypertension"],
    allergies: ["ACE Inhibitors (cough)"],
    requiredTreatment: "Emergency hemodialysis, calcium gluconate cardiac stabilization, insulin-dextrose shift",
    emergencyStatus: true,
    urgencyLevel: "HIGH",
    priorityScore: 79,
    priorityExplanation: "HIGH urgency (+70) with life-threatening hyperkalemia (K+ 6.8) and ECG conduction changes.",
    waitingMinutes: 55,
    status: "ALLOCATED",
    createdAt: minsAgo(55),
    updatedAt: minsAgo(15),
  },
  {
    id: "pat-in-10",
    mrn: "MRN-BLR-2026-090",
    name: "Kavya Shetty",
    age: 31,
    gender: "Female",
    contact: "+91 98455 12098",
    arrivalTime: minsAgo(40),
    symptoms: "Primi gravida at 34 weeks gestation with severe throbbing frontal headache, scotomata, and facial edema",
    clinicalNotes: "Blood pressure 168/110 mmHg on two separate readings. Urine dipstick 3+ proteinuria. Severe pre-eclampsia with impending eclampsia signs.",
    departmentId: "dept-obg",
    departmentName: "Obstetrics & Gynecology",
    vitalSigns: { heartRate: 88, bloodPressureSystolic: 168, bloodPressureDiastolic: 110, oxygenSaturation: 98, respiratoryRate: 18, temperatureCelsius: 37.0 },
    knownConditions: ["Gestational Hypertension"],
    allergies: ["None"],
    requiredTreatment: "Magnesium sulfate seizure prophylaxis protocol, IV Labetalol, continuous fetal cardiotocography",
    emergencyStatus: true,
    urgencyLevel: "HIGH",
    priorityScore: 76,
    priorityExplanation: "HIGH urgency (+70) with maternal-fetal risk from severe pre-eclampsia.",
    waitingMinutes: 40,
    status: "ALLOCATED",
    createdAt: minsAgo(40),
    updatedAt: minsAgo(10),
  },
  {
    id: "pat-in-11",
    mrn: "MRN-BLR-2026-091",
    name: "Meera Krishnan",
    age: 6,
    gender: "Female",
    contact: "+91 98412 88712",
    arrivalTime: minsAgo(15),
    symptoms: "High fever (39.8°C), rapid breathing with intercostal retractions, lethargy, poor oral fluid intake",
    clinicalNotes: "Bilateral crepitations with right middle lobe bronchial breath sounds. Suspected severe lobar pneumonia in pediatric patient. Pediatrician attending.",
    departmentId: "dept-ped",
    departmentName: "Pediatrics & Neonatology",
    vitalSigns: { heartRate: 142, bloodPressureSystolic: 92, bloodPressureDiastolic: 58, oxygenSaturation: 92, respiratoryRate: 46, temperatureCelsius: 39.8 },
    knownConditions: ["Childhood Asthma"],
    allergies: ["None"],
    requiredTreatment: "Humidified high-flow oxygen, IV third-generation cephalosporin, pediatric inpatient bed",
    emergencyStatus: true,
    urgencyLevel: "HIGH",
    priorityScore: 74,
    priorityExplanation: "HIGH urgency (+70) with pediatric respiratory distress and hypoxia (SpO2 92%).",
    waitingMinutes: 15,
    status: "ALLOCATED",
    createdAt: minsAgo(15),
    updatedAt: minsAgo(3),
  },
  {
    id: "pat-in-12",
    mrn: "MRN-BLR-2026-092",
    name: "Rahul Verma",
    age: 42,
    gender: "Male",
    contact: "+91 98101 22345",
    arrivalTime: minsAgo(35),
    symptoms: "Severe acute asthma exacerbation, speaking in single words, widespread expiratory wheeze, exhaustion",
    clinicalNotes: "Peak expiratory flow <40% of predicted. Not responding to home salbutamol inhaler. Clinically assessed for impending respiratory fatigue.",
    departmentId: "dept-pulmo",
    departmentName: "Pulmonology",
    vitalSigns: { heartRate: 114, bloodPressureSystolic: 134, bloodPressureDiastolic: 86, oxygenSaturation: 91, respiratoryRate: 30, temperatureCelsius: 37.1 },
    knownConditions: ["Bronchial Asthma since childhood"],
    allergies: ["Ibuprofen / NSAIDs"],
    requiredTreatment: "Continuous nebulization with salbutamol and ipratropium, IV hydrocortisone, magnesium sulfate infusion",
    emergencyStatus: true,
    urgencyLevel: "HIGH",
    priorityScore: 72,
    priorityExplanation: "HIGH urgency (+70) with acute severe bronchospasm and poor air entry.",
    waitingMinutes: 35,
    status: "ALLOCATED",
    createdAt: minsAgo(35),
    updatedAt: minsAgo(8),
  },

  // ================= MODERATE URGENCY PATIENTS (~40%) =================
  {
    id: "pat-in-13",
    mrn: "MRN-BLR-2026-093",
    name: "Nandini Krishnan",
    age: 34,
    gender: "Female",
    contact: "+91 98402 33451",
    arrivalTime: minsAgo(42),
    symptoms: "Fever for 3 days (38.8°C), generalized myalgia, severe retro-orbital ache, nausea, weakness",
    clinicalNotes: "Patient arrived via outpatient triage. Febrile illness under evaluation (suspected dengue vs viral illness). Vitals stable, hydration required.",
    departmentId: "dept-med",
    departmentName: "General Medicine",
    vitalSigns: { heartRate: 88, bloodPressureSystolic: 110, bloodPressureDiastolic: 70, oxygenSaturation: 98, respiratoryRate: 18, temperatureCelsius: 38.8 },
    knownConditions: ["None"],
    allergies: ["None"],
    requiredTreatment: "CBC, Dengue NS1 & IgM serology, IV fluid hydration, oral paracetamol",
    emergencyStatus: false,
    urgencyLevel: "MODERATE",
    priorityScore: 48,
    priorityExplanation: "MODERATE urgency (+40) with 42-min wait aging (+8). Hydration and serial hematocrit tracking indicated.",
    waitingMinutes: 42,
    status: "ALLOCATED",
    createdAt: minsAgo(42),
    updatedAt: minsAgo(15),
  },
  {
    id: "pat-in-14",
    mrn: "MRN-BLR-2026-094",
    name: "Arjun Rao",
    age: 45,
    gender: "Male",
    contact: "+91 98801 67432",
    arrivalTime: minsAgo(28),
    symptoms: "Crampy lower quadrant abdominal pain, frequent loose stools with mucus for 36 hours, moderate dehydration",
    clinicalNotes: "Acute gastroenteritis under evaluation. Dry oral mucosa, reduced skin turgor. No peritoneal signs. Stool routine and electrolytes requested.",
    departmentId: "dept-med",
    departmentName: "General Medicine",
    vitalSigns: { heartRate: 96, bloodPressureSystolic: 104, bloodPressureDiastolic: 68, oxygenSaturation: 99, respiratoryRate: 18, temperatureCelsius: 38.1 },
    knownConditions: ["None"],
    allergies: ["None"],
    requiredTreatment: "IV Ringer Lactate fluid replenishment, anti-spasmodic, stool culture",
    emergencyStatus: false,
    urgencyLevel: "MODERATE",
    priorityScore: 44,
    priorityExplanation: "MODERATE urgency (+40) with dehydration and ongoing gastrointestinal losses.",
    waitingMinutes: 28,
    status: "ALLOCATED",
    createdAt: minsAgo(28),
    updatedAt: minsAgo(10),
  },
  {
    id: "pat-in-15",
    mrn: "MRN-BLR-2026-095",
    name: "Neha Joshi",
    age: 28,
    gender: "Female",
    contact: "+91 98205 91823",
    arrivalTime: minsAgo(64),
    symptoms: "Severe throbbing unilateral hemicranial headache with photophobia, nausea, and vomiting for 12 hours",
    clinicalNotes: "Acute migraine exacerbation refractory to oral medications. Neurological examination normal. No meningeal signs.",
    departmentId: "dept-med",
    departmentName: "General Medicine",
    vitalSigns: { heartRate: 82, bloodPressureSystolic: 118, bloodPressureDiastolic: 76, oxygenSaturation: 99, respiratoryRate: 16, temperatureCelsius: 36.8 },
    knownConditions: ["Chronic Migraine with Aura"],
    allergies: ["Metoclopramide (extrapyramidal symptoms)"],
    requiredTreatment: "Quiet room bed, IV fluids, IV NSAID analgesia, anti-emetic",
    emergencyStatus: false,
    urgencyLevel: "MODERATE",
    priorityScore: 52,
    priorityExplanation: "MODERATE urgency (+40) with extended 64-min wait (+12 pts anti-starvation).",
    waitingMinutes: 64,
    status: "WAITING",
    createdAt: minsAgo(64),
    updatedAt: minsAgo(1),
  },
  {
    id: "pat-in-16",
    mrn: "MRN-BLR-2026-096",
    name: "Pooja Deshmukh",
    age: 52,
    gender: "Female",
    contact: "+91 98210 11928",
    arrivalTime: minsAgo(48),
    symptoms: "High fever with rigors, right flank pain, burning micturition, nausea for 2 days",
    clinicalNotes: "Marked right costovertebral angle tenderness. Suspected acute pyelonephritis under evaluation. Urine analysis shows pyuria and bacteriuria.",
    departmentId: "dept-med",
    departmentName: "General Medicine",
    vitalSigns: { heartRate: 98, bloodPressureSystolic: 114, bloodPressureDiastolic: 72, oxygenSaturation: 98, respiratoryRate: 20, temperatureCelsius: 39.0 },
    knownConditions: ["Type 2 Diabetes Mellitus"],
    allergies: ["Ciprofloxacin"],
    requiredTreatment: "IV Ceftriaxone, analgesics, blood and urine cultures, renal ultrasound",
    emergencyStatus: false,
    urgencyLevel: "MODERATE",
    priorityScore: 49,
    priorityExplanation: "MODERATE urgency (+40) with upper urinary tract infection and fever.",
    waitingMinutes: 48,
    status: "TRIAGED",
    createdAt: minsAgo(48),
    updatedAt: minsAgo(5),
  },
  {
    id: "pat-in-17",
    mrn: "MRN-BLR-2026-097",
    name: "Harish Kumar",
    age: 60,
    gender: "Male",
    contact: "+91 98451 90812",
    arrivalTime: minsAgo(34),
    symptoms: "Colicky right upper quadrant pain radiating to back after rich dinner, nausea, mild scleral icterus",
    clinicalNotes: "Murphy's sign positive. Suspected acute calculous cholecystitis under evaluation. Liver function tests and USG Hepatobiliary ordered.",
    departmentId: "dept-surg",
    departmentName: "General Surgery",
    vitalSigns: { heartRate: 86, bloodPressureSystolic: 138, bloodPressureDiastolic: 84, oxygenSaturation: 97, respiratoryRate: 18, temperatureCelsius: 38.0 },
    knownConditions: ["Cholelithiasis known for 1 year"],
    allergies: ["None"],
    requiredTreatment: "Biliary ultrasound, IV antibiotics, bowel rest, surgical consultation",
    emergencyStatus: false,
    urgencyLevel: "MODERATE",
    priorityScore: 46,
    priorityExplanation: "MODERATE urgency (+40) with acute biliary colic and localized inflammation.",
    waitingMinutes: 34,
    status: "TRIAGED",
    createdAt: minsAgo(34),
    updatedAt: minsAgo(6),
  },
  {
    id: "pat-in-18",
    mrn: "MRN-BLR-2026-098",
    name: "Nikhil Bhat",
    age: 22,
    gender: "Male",
    contact: "+91 98862 33109",
    arrivalTime: minsAgo(19),
    symptoms: "Severe right wrist deformity, swelling, and acute pain after fall on outstretched hand while playing cricket",
    clinicalNotes: "Colles fracture suspected. Neurovascular examination intact in fingers. X-Ray wrist AP and lateral requested. Immobilized with temporary splint.",
    departmentId: "dept-ortho",
    departmentName: "Orthopedics",
    vitalSigns: { heartRate: 82, bloodPressureSystolic: 122, bloodPressureDiastolic: 76, oxygenSaturation: 99, respiratoryRate: 16, temperatureCelsius: 36.9 },
    knownConditions: ["None"],
    allergies: ["None"],
    requiredTreatment: "Orthopedic reduction under hematoma block, plaster of Paris cast application",
    emergencyStatus: false,
    urgencyLevel: "MODERATE",
    priorityScore: 43,
    priorityExplanation: "MODERATE urgency (+40) with closed fracture and pain requiring reduction.",
    waitingMinutes: 19,
    status: "WAITING",
    createdAt: minsAgo(19),
    updatedAt: minsAgo(4),
  },
  {
    id: "pat-in-19",
    mrn: "MRN-BLR-2026-099",
    name: "Divya Srinivasan",
    age: 33,
    gender: "Female",
    contact: "+91 98403 99881",
    arrivalTime: minsAgo(52),
    symptoms: "Acute vertigo with rotatory sensations, nausea, horizontal nystagmus on head movement, unable to walk unassisted",
    clinicalNotes: "Benign Paroxysmal Positional Vertigo (BPPV) vs acute vestibular neuritis under evaluation. Dix-Hallpike maneuver planned once anti-emetics administered.",
    departmentId: "dept-med",
    departmentName: "General Medicine",
    vitalSigns: { heartRate: 76, bloodPressureSystolic: 116, bloodPressureDiastolic: 74, oxygenSaturation: 99, respiratoryRate: 16, temperatureCelsius: 36.7 },
    knownConditions: ["None"],
    allergies: ["None"],
    requiredTreatment: "Vestibular sedatives, Canalith repositioning maneuver (Epley), anti-emetic support",
    emergencyStatus: false,
    urgencyLevel: "MODERATE",
    priorityScore: 47,
    priorityExplanation: "MODERATE urgency (+40) with incapacitating vertigo and fall risk.",
    waitingMinutes: 52,
    status: "WAITING",
    createdAt: minsAgo(52),
    updatedAt: minsAgo(2),
  },
  {
    id: "pat-in-20",
    mrn: "MRN-BLR-2026-100",
    name: "Manish Gupta",
    age: 49,
    gender: "Male",
    contact: "+91 98112 45671",
    arrivalTime: minsAgo(36),
    symptoms: "Step-ladder fever for 6 days, dull frontal headache, relative bradycardia, abdominal bloating, constipation",
    clinicalNotes: "Suspected enteric fever (typhoid) under evaluation. Coated tongue, mild splenomegaly palpable. Widal and blood culture dispatched.",
    departmentId: "dept-med",
    departmentName: "General Medicine",
    vitalSigns: { heartRate: 72, bloodPressureSystolic: 120, bloodPressureDiastolic: 78, oxygenSaturation: 98, respiratoryRate: 18, temperatureCelsius: 39.1 },
    knownConditions: ["None"],
    allergies: ["None"],
    requiredTreatment: "Blood cultures, IV Azithromycin / Ceftriaxone, hydration and dietary management",
    emergencyStatus: false,
    urgencyLevel: "MODERATE",
    priorityScore: 46,
    priorityExplanation: "MODERATE urgency (+40) with persistent high bacteremic fever.",
    waitingMinutes: 36,
    status: "TRIAGED",
    createdAt: minsAgo(36),
    updatedAt: minsAgo(8),
  },

  // ================= LOW URGENCY PATIENTS (~25%) =================
  {
    id: "pat-in-21",
    mrn: "MRN-BLR-2026-101",
    name: "Aditi Kapoor",
    age: 24,
    gender: "Female",
    contact: "+91 98115 67890",
    arrivalTime: minsAgo(46),
    symptoms: "Superficial 3cm laceration over left forearm sustained while chopping vegetables at home, bleeding controlled",
    clinicalNotes: "Clean sharp margin laceration. Sensation intact distally, no tendon involvement. Tetanus toxoid status updated.",
    departmentId: "dept-er",
    departmentName: "Emergency & Trauma",
    vitalSigns: { heartRate: 74, bloodPressureSystolic: 112, bloodPressureDiastolic: 70, oxygenSaturation: 99, respiratoryRate: 14, temperatureCelsius: 36.6 },
    knownConditions: ["None"],
    allergies: ["None"],
    requiredTreatment: "Wound irrigation, local anesthesia, nylon primary suture closure, sterile dressing",
    emergencyStatus: false,
    urgencyLevel: "LOW",
    priorityScore: 28,
    priorityExplanation: "LOW urgency (+20) with simple stable superficial laceration.",
    waitingMinutes: 46,
    status: "WAITING",
    createdAt: minsAgo(46),
    updatedAt: minsAgo(1),
  },
  {
    id: "pat-in-22",
    mrn: "MRN-BLR-2026-102",
    name: "Suresh Hegde",
    age: 56,
    gender: "Male",
    contact: "+91 98863 12450",
    arrivalTime: minsAgo(58),
    symptoms: "Routine review for essential hypertension, mild intermittent occipital heaviness after stressful work week",
    clinicalNotes: "Blood pressure 144/90 mmHg. Ambulatory review. Medication compliance review indicated. Fundoscopy normal.",
    departmentId: "dept-med",
    departmentName: "General Medicine",
    vitalSigns: { heartRate: 70, bloodPressureSystolic: 144, bloodPressureDiastolic: 90, oxygenSaturation: 98, respiratoryRate: 16, temperatureCelsius: 36.7 },
    knownConditions: ["Essential Hypertension"],
    allergies: ["None"],
    requiredTreatment: "Physician consultation, prescription adjustment, lifestyle counseling",
    emergencyStatus: false,
    urgencyLevel: "LOW",
    priorityScore: 29,
    priorityExplanation: "LOW urgency (+20) with stable outpatient chronic disease follow-up.",
    waitingMinutes: 58,
    status: "WAITING",
    createdAt: minsAgo(58),
    updatedAt: minsAgo(3),
  },
  {
    id: "pat-in-23",
    mrn: "MRN-BLR-2026-103",
    name: "Deepak Choudhury",
    age: 39,
    gender: "Male",
    contact: "+91 98301 44567",
    arrivalTime: minsAgo(24),
    symptoms: "Sore throat, nasal congestion, low-grade malaise for 2 days, mild dry cough",
    clinicalNotes: "Viral upper respiratory tract infection. Mild pharyngeal erythema, no tonsillar exudate. Cervical lymph nodes not enlarged.",
    departmentId: "dept-med",
    departmentName: "General Medicine",
    vitalSigns: { heartRate: 72, bloodPressureSystolic: 118, bloodPressureDiastolic: 74, oxygenSaturation: 99, respiratoryRate: 14, temperatureCelsius: 37.4 },
    knownConditions: ["None"],
    allergies: ["None"],
    requiredTreatment: "Symptomatic relief, saline gargles, steam inhalation, antihistamines",
    emergencyStatus: false,
    urgencyLevel: "LOW",
    priorityScore: 24,
    priorityExplanation: "LOW urgency (+20) with uncomplicated viral pharyngitis.",
    waitingMinutes: 24,
    status: "WAITING",
    createdAt: minsAgo(24),
    updatedAt: minsAgo(2),
  },
  {
    id: "pat-in-24",
    mrn: "MRN-BLR-2026-104",
    name: "Pallavi Deshpande",
    age: 35,
    gender: "Female",
    contact: "+91 98221 77890",
    arrivalTime: minsAgo(32),
    symptoms: "Mild burning epigastric discomfort after spicy meals, occasional acid regurgitation",
    clinicalNotes: "Non-ulcer dyspepsia. Abdomen soft, non-tender. No red flags like weight loss or dysphagia.",
    departmentId: "dept-med",
    departmentName: "General Medicine",
    vitalSigns: { heartRate: 68, bloodPressureSystolic: 114, bloodPressureDiastolic: 72, oxygenSaturation: 100, respiratoryRate: 14, temperatureCelsius: 36.6 },
    knownConditions: ["None"],
    allergies: ["None"],
    requiredTreatment: "Proton pump inhibitor trial, dietary counseling",
    emergencyStatus: false,
    urgencyLevel: "LOW",
    priorityScore: 25,
    priorityExplanation: "LOW urgency (+20) with mild outpatient gastrointestinal complaints.",
    waitingMinutes: 32,
    status: "WAITING",
    createdAt: minsAgo(32),
    updatedAt: minsAgo(5),
  },
  {
    id: "pat-in-25",
    mrn: "MRN-BLR-2026-105",
    name: "Karthik Sundaram",
    age: 21,
    gender: "Male",
    contact: "+91 98404 11233",
    arrivalTime: minsAgo(20),
    symptoms: "Inversion sprain of right lateral ankle while stepping off BMTC bus, mild edema over anterior talofibular ligament",
    clinicalNotes: "Grade I lateral ankle sprain. Able to bear weight. Ottawa ankle rules negative for fracture. Ice and compression applied.",
    departmentId: "dept-ortho",
    departmentName: "Orthopedics",
    vitalSigns: { heartRate: 76, bloodPressureSystolic: 120, bloodPressureDiastolic: 76, oxygenSaturation: 99, respiratoryRate: 14, temperatureCelsius: 36.8 },
    knownConditions: ["None"],
    allergies: ["None"],
    requiredTreatment: "RICE therapy protocol, crepe bandage immobilization, oral paracetamol",
    emergencyStatus: false,
    urgencyLevel: "LOW",
    priorityScore: 23,
    priorityExplanation: "LOW urgency (+20) with minor soft tissue ligament sprain.",
    waitingMinutes: 20,
    status: "WAITING",
    createdAt: minsAgo(20),
    updatedAt: minsAgo(2),
  },

  // ================= HISTORICAL DISCHARGED PATIENTS (For Analytics Throughput) =================
  {
    id: "pat-in-26",
    mrn: "MRN-BLR-2026-071",
    name: "Ravi Shankar",
    age: 44,
    gender: "Male",
    contact: "+91 98452 77810",
    arrivalTime: minsAgo(380),
    symptoms: "Acute left ureteric colic pain, microscopic hematuria",
    clinicalNotes: "Confirmed 4mm left distal ureteric calculus on non-contrast CT. Pain relieved with IV Ketorolac. Good urine output.",
    departmentId: "dept-nephro",
    departmentName: "Nephrology & Hemodialysis",
    vitalSigns: { heartRate: 72, bloodPressureSystolic: 122, bloodPressureDiastolic: 78, oxygenSaturation: 99, respiratoryRate: 16, temperatureCelsius: 36.8 },
    knownConditions: ["Renal calculi"],
    allergies: ["None"],
    requiredTreatment: "Medical expulsive therapy (Tamsulosin), hydration, outpatient urology follow-up",
    emergencyStatus: false,
    urgencyLevel: "MODERATE",
    priorityScore: 40,
    priorityExplanation: "Clinically stable post-conservative management.",
    waitingMinutes: 14,
    status: "DISCHARGED",
    createdAt: minsAgo(380),
    updatedAt: minsAgo(60),
  },
  {
    id: "pat-in-27",
    mrn: "MRN-BLR-2026-072",
    name: "Sunita Deshmukh",
    age: 37,
    gender: "Female",
    contact: "+91 98211 44521",
    arrivalTime: minsAgo(420),
    symptoms: "Mild acute exacerbation of allergic rhinitis with non-productive cough",
    clinicalNotes: "Chest clear on auscultation. Symptomatically improved with inhaled bronchodilator in observation bay.",
    departmentId: "dept-med",
    departmentName: "General Medicine",
    vitalSigns: { heartRate: 74, bloodPressureSystolic: 116, bloodPressureDiastolic: 74, oxygenSaturation: 99, respiratoryRate: 16, temperatureCelsius: 36.6 },
    knownConditions: ["Allergic Rhinitis"],
    allergies: ["Dust mites"],
    requiredTreatment: "Antihistamine, nasal steroid spray, discharged home with instructions",
    emergencyStatus: false,
    urgencyLevel: "LOW",
    priorityScore: 20,
    priorityExplanation: "Successfully discharged home.",
    waitingMinutes: 12,
    status: "DISCHARGED",
    createdAt: minsAgo(420),
    updatedAt: minsAgo(120),
  },
  {
    id: "pat-in-28",
    mrn: "MRN-BLR-2026-073",
    name: "Babu Rajendran",
    age: 68,
    gender: "Male",
    contact: "+91 98405 88912",
    arrivalTime: minsAgo(490),
    symptoms: "Transient ischemic attack (resolved left arm weakness lasting 20 minutes)",
    clinicalNotes: "MRI Brain diffusion-weighted imaging negative for acute infarction. Carotid Doppler shows <30% stenosis. Started on antiplatelet therapy.",
    departmentId: "dept-neuro",
    departmentName: "Neurology",
    vitalSigns: { heartRate: 76, bloodPressureSystolic: 136, bloodPressureDiastolic: 82, oxygenSaturation: 98, respiratoryRate: 16, temperatureCelsius: 36.9 },
    knownConditions: ["Hypertension", "Dyslipidemia"],
    allergies: ["None"],
    requiredTreatment: "Antiplatelet therapy, statin, neurology outpatient review in 1 week",
    emergencyStatus: true,
    urgencyLevel: "HIGH",
    priorityScore: 70,
    priorityExplanation: "Stable post 6-hour observation protocol.",
    waitingMinutes: 18,
    status: "DISCHARGED",
    createdAt: minsAgo(490),
    updatedAt: minsAgo(140),
  },
  {
    id: "pat-in-29",
    mrn: "MRN-BLR-2026-074",
    name: "Kavitha Murthy",
    age: 29,
    gender: "Female",
    contact: "+91 98453 11029",
    arrivalTime: minsAgo(340),
    symptoms: "Mild acute food poisoning, single episode vomiting after street food, no fever",
    clinicalNotes: "Hydrated with oral rehydration solution. Vitals normal. Patient tolerating light oral diet.",
    departmentId: "dept-med",
    departmentName: "General Medicine",
    vitalSigns: { heartRate: 70, bloodPressureSystolic: 110, bloodPressureDiastolic: 70, oxygenSaturation: 100, respiratoryRate: 14, temperatureCelsius: 36.7 },
    knownConditions: ["None"],
    allergies: ["None"],
    requiredTreatment: "Oral rehydration, anti-emetic, discharged home",
    emergencyStatus: false,
    urgencyLevel: "LOW",
    priorityScore: 20,
    priorityExplanation: "Resolved acute gastroenteritis.",
    waitingMinutes: 15,
    status: "DISCHARGED",
    createdAt: minsAgo(340),
    updatedAt: minsAgo(80),
  },
];

export const SEED_ALLOCATIONS: ResourceAllocation[] = [
  {
    id: "alloc-in-01",
    patientId: "pat-in-01",
    patientName: "Ramesh Gowda",
    patientUrgency: "CRITICAL",
    resourceId: "res-er-01",
    resourceNumber: "ER-01",
    resourceName: "Emergency Resuscitation Bay 1",
    resourceType: "BED",
    quantity: 1,
    startTime: minsAgo(15),
    expectedEndTime: new Date(Date.now() + 120 * 60 * 1000).toISOString(),
    allocatedBy: "Dr. Anirudh Rao",
    allocationReason: "Acute STEMI resuscitation and continuous cardiac telemetry",
    priorityAtAllocation: 98,
    status: "ACTIVE",
  },
  {
    id: "alloc-in-02",
    patientId: "pat-in-01",
    patientName: "Ramesh Gowda",
    patientUrgency: "CRITICAL",
    resourceId: "res-cm-01",
    resourceNumber: "CM-01",
    resourceName: "Mindray BeneVision Multi-Parameter Monitor",
    resourceType: "EQUIPMENT",
    quantity: 1,
    startTime: minsAgo(15),
    expectedEndTime: new Date(Date.now() + 120 * 60 * 1000).toISOString(),
    allocatedBy: "Dr. Anirudh Rao",
    allocationReason: "Continuous 12-lead arrhythmia detection and blood pressure tracking",
    priorityAtAllocation: 98,
    status: "ACTIVE",
  },
  {
    id: "alloc-in-03",
    patientId: "pat-in-02",
    patientName: "Mohammed Farooq",
    patientUrgency: "CRITICAL",
    resourceId: "res-icu-01",
    resourceNumber: "ICU-01",
    resourceName: "ICU Bed 01 (Isolation Negative Pressure)",
    resourceType: "ICU_BED",
    quantity: 1,
    startTime: minsAgo(40),
    expectedEndTime: new Date(Date.now() + 360 * 60 * 1000).toISOString(),
    allocatedBy: "Dr. Vivek Nair",
    allocationReason: "Severe pneumonia with hypoxemic respiratory failure and septic shock",
    priorityAtAllocation: 104,
    status: "ACTIVE",
  },
  {
    id: "alloc-in-04",
    patientId: "pat-in-02",
    patientName: "Mohammed Farooq",
    patientUrgency: "CRITICAL",
    resourceId: "res-vent-01",
    resourceNumber: "VENT-01",
    resourceName: "Hamilton C6 Intensive Ventilator",
    resourceType: "VENTILATOR",
    quantity: 1,
    startTime: minsAgo(40),
    expectedEndTime: new Date(Date.now() + 360 * 60 * 1000).toISOString(),
    allocatedBy: "Dr. Vivek Nair",
    allocationReason: "Mechanical invasive ventilation for acute ARDS physiology",
    priorityAtAllocation: 104,
    status: "ACTIVE",
  },
  {
    id: "alloc-in-05",
    patientId: "pat-in-03",
    patientName: "Vikram Reddy",
    patientUrgency: "CRITICAL",
    resourceId: "res-er-02",
    resourceNumber: "ER-02",
    resourceName: "Emergency Acute Bay 2",
    resourceType: "BED",
    quantity: 1,
    startTime: minsAgo(20),
    expectedEndTime: new Date(Date.now() + 90 * 60 * 1000).toISOString(),
    allocatedBy: "Dr. Arvind Reddy",
    allocationReason: "Polytrauma resuscitation and pre-operative damage control stabilization",
    priorityAtAllocation: 96,
    status: "ACTIVE",
  },
  {
    id: "alloc-in-06",
    patientId: "pat-in-04",
    patientName: "Lakshmi Narayanan",
    patientUrgency: "CRITICAL",
    resourceId: "res-icu-02",
    resourceNumber: "ICU-02",
    resourceName: "ICU Bed 02",
    resourceType: "ICU_BED",
    quantity: 1,
    startTime: minsAgo(55),
    expectedEndTime: new Date(Date.now() + 240 * 60 * 1000).toISOString(),
    allocatedBy: "Dr. Shreya Kulkarni",
    allocationReason: "Post-thrombolysis neurological surveillance and hemodynamic control",
    priorityAtAllocation: 94,
    status: "ACTIVE",
  },
  {
    id: "alloc-in-07",
    patientId: "pat-in-05",
    patientName: "Priya Menon",
    patientUrgency: "HIGH",
    resourceId: "res-or-01",
    resourceNumber: "OR-01",
    resourceName: "Major Operation Theatre 1 (Emergency Trauma)",
    resourceType: "OPERATING_ROOM",
    quantity: 1,
    startTime: minsAgo(30),
    expectedEndTime: new Date(Date.now() + 60 * 60 * 1000).toISOString(),
    allocatedBy: "Dr. Arvind Reddy",
    allocationReason: "Emergency laparoscopic appendectomy for gangrenous appendicitis",
    priorityAtAllocation: 78,
    status: "ACTIVE",
  },
  {
    id: "alloc-in-08",
    patientId: "pat-in-08",
    patientName: "Ananya Iyer",
    patientUrgency: "HIGH",
    resourceId: "res-gb-05",
    resourceNumber: "GB-05",
    resourceName: "Cardiology Telemetry Bed 05",
    resourceType: "BED",
    quantity: 1,
    startTime: minsAgo(20),
    expectedEndTime: new Date(Date.now() + 300 * 60 * 1000).toISOString(),
    allocatedBy: "Dr. Kavitha Menon",
    allocationReason: "Telemetry inpatient bed for NSTEMI acute evaluation",
    priorityAtAllocation: 73,
    status: "ACTIVE",
  },
  {
    id: "alloc-in-09",
    patientId: "pat-in-09",
    patientName: "Sanjay Patil",
    patientUrgency: "HIGH",
    resourceId: "res-dia-01",
    resourceNumber: "DIA-01",
    resourceName: "Fresenius 4008S Hemodialysis Machine",
    resourceType: "EQUIPMENT",
    quantity: 1,
    startTime: minsAgo(45),
    expectedEndTime: new Date(Date.now() + 180 * 60 * 1000).toISOString(),
    allocatedBy: "Dr. Sanjay Patil",
    allocationReason: "Emergency hemodialysis session for hyperkalemia K+ 6.8",
    priorityAtAllocation: 79,
    status: "ACTIVE",
  },
  {
    id: "alloc-in-10",
    patientId: "pat-in-13",
    patientName: "Nandini Krishnan",
    patientUrgency: "MODERATE",
    resourceId: "res-gb-01",
    resourceNumber: "GB-01",
    resourceName: "General Ward Bed 01",
    resourceType: "BED",
    quantity: 1,
    startTime: minsAgo(30),
    expectedEndTime: new Date(Date.now() + 480 * 60 * 1000).toISOString(),
    allocatedBy: "Dr. Harish Kumar",
    allocationReason: "Hydration and inpatient febrile evaluation",
    priorityAtAllocation: 48,
    status: "ACTIVE",
  },
];

export const SEED_AUDIT_LOGS: AuditEvent[] = [
  {
    id: "audit-init-01",
    userId: "system",
    userName: "Dr. Arvind Reddy",
    performedBy: "Dr. Arvind Reddy",
    userRole: "ADMIN",
    action: "SYSTEM_INITIALIZED",
    timestamp: minsAgo(120),
    entityType: "HospitalFacility",
    entityId: "shantideep-blr",
    reason: "Initialized Shantideep Multispeciality Hospital clinical operating system for Bengaluru facility.",
  },
  {
    id: "audit-init-02",
    userId: "doc-01",
    userName: "Dr. Anirudh Rao",
    performedBy: "Dr. Anirudh Rao",
    userRole: "DOCTOR",
    action: "RESOURCE_ALLOCATED",
    timestamp: minsAgo(15),
    entityType: "ResourceAllocation",
    entityId: "alloc-in-01",
    reason: "Assigned Emergency Resuscitation Bay 1 (ER-01) to acute STEMI patient Ramesh Gowda.",
  },
  {
    id: "audit-init-03",
    userId: "doc-03",
    userName: "Dr. Vivek Nair",
    performedBy: "Dr. Vivek Nair",
    userRole: "DOCTOR",
    action: "RESOURCE_ALLOCATED",
    timestamp: minsAgo(40),
    entityType: "ResourceAllocation",
    entityId: "alloc-in-03",
    reason: "Assigned ICU Bed 01 and Ventilator VENT-01 to critical ARDS patient Mohammed Farooq.",
  },
  {
    id: "audit-init-04",
    userId: "nurse-01",
    userName: "Deepa Nair, RN",
    performedBy: "Deepa Nair, RN",
    userRole: "NURSE",
    action: "TRIAGE_COMPLETED",
    timestamp: minsAgo(35),
    entityType: "Patient",
    entityId: "pat-in-06",
    reason: "Completed triage for Sneha Kulkarni; elevated to HIGH urgency due to severe thrombocytopenia.",
  },
];
